version: '3'

services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pgpass
            POSTGRES_DB: guestbook1
        ports: [5432]
    mailer:
        image: schickling/mailcatcher
        ports: [ 1025, 1080 ]
